### ISSUE TITLE
Tabnabbing in HTML

### ISSUE THREAD

**Issue by 3th1cyuk1** [thundergolfer/thundergolfer.github.io#10]
The following HTML code only has target=_blank parameter which could lead to tabnabbing, the user unknowingly gets redirected to another website at the background it should be advised to include rel=noopener like protectors

**Comment by thundergolfer** [comment]
> The following HTML code

which bit of HTML? 

I haven't heard of tabnabbing before, but I'll look into it, thanks.

**Comment by thundergolfer** [comment]
Fixed on latest `master`. Thanks for the heads up.
