### ISSUE TITLE
Add shadow underneath dropdown menu

### ISSUE THREAD

**Issue by thundergolfer** [thundergolfer/thundergolfer.github.io#7]
Makes it easier to tell that the menu is an overlay.

**Comment by MridulTailor** [comment]
Hey Thundergolfer, I added a shadow underneath the dropdown menu, attaching the image assign me if you like me to do this 
![Screenshot 2021-07-04 163059](https://user-images.githubusercontent.com/71081929/124382585-dd19a900-dce5-11eb-9bd6-5e5a2e5a5333.jpg)
Thank you.

**Comment by MridulTailor** [comment]
Hey Thundergolfer, I would like to work on this issue. After I fix this issue it will look like in the image attached. Thank You.
![Shadowed-Menu-Dropdown](https://user-images.githubusercontent.com/71081929/124382738-9d9f8c80-dce6-11eb-9981-034c726bbbb4.jpg)

**Comment by thundergolfer** [comment]
If you'd like to, sure 😃

**Comment by MridulTailor** [comment]
Hi thundergolfer.  I made a commit on this issue. Check it out.
